# Generated by Django 5.2.4 on 2025-08-13 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('manager', 'Manager'), ('qa', 'QA'), ('intern', 'Intern')], max_length=30)),
                ('permissions', models.CharField(choices=[('all', 'All Permissions'), ('limited', 'Limited Permissions'), ('view_only', 'View Only')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
