# Generated by Django 5.2.4 on 2025-08-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeecontract_renewal_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='employees/certifications/'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='document',
            field=models.FileField(upload_to='employees/contracts/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='meta',
            field=models.CharField(blank=True, null=True),
        ),
    ]
