# Generated by Django 5.2.4 on 2025-08-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_certification_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='meta',
            field=models.CharField(blank=True, null=True),
        ),
    ]
