# Generated by Django 5.2.4 on 2025-08-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_certification_meta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourceassignment',
            unique_together=set(),
        ),
    ]
