# Generated by Django 5.2.4 on 2025-08-20 11:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='CashFlowReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('is_finalized', models.BooleanField(default=False)),
                ('base_currency', models.CharField(default='INR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_inflow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_outflow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_analytics.financialperiod')),
            ],
            options={
                'abstract': False,
                'unique_together': {('period', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ForecastReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('is_finalized', models.BooleanField(default=False)),
                ('base_currency', models.CharField(default='INR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecasted_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('forecasted_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('forecasted_net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_analytics.financialperiod')),
            ],
            options={
                'abstract': False,
                'unique_together': {('period', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PartnerFinancialBreakdown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('is_finalized', models.BooleanField(default=False)),
                ('base_currency', models.CharField(default='INR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_analytics.financialperiod')),
            ],
            options={
                'abstract': False,
                'unique_together': {('partner', 'period', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ProfitLossReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('is_finalized', models.BooleanField(default=False)),
                ('base_currency', models.CharField(default='INR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_analytics.financialperiod')),
            ],
            options={
                'abstract': False,
                'unique_together': {('period', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('is_finalized', models.BooleanField(default=False)),
                ('base_currency', models.CharField(default='INR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_taxable_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_analytics.financialperiod')),
            ],
            options={
                'abstract': False,
                'unique_together': {('period', 'version')},
            },
        ),
    ]
