# Generated by Django 5.2.4 on 2025-08-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxreport',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='taxreport',
            name='total_taxable_income',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
