# Generated by Django 5.2.4 on 2025-08-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analytics', '0002_alter_taxreport_total_deductions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastreport',
            options={'verbose_name': 'Forecast Report', 'verbose_name_plural': 'Forecast Reports'},
        ),
        migrations.AlterUniqueTogether(
            name='forecastreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='expected_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='forecasted_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forecastreport',
            name='forecasted_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='forecastreport',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_reports', to='financial_analytics.financialperiod'),
        ),
        migrations.RemoveField(
            model_name='forecastreport',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='forecastreport',
            name='forecasted_expense',
        ),
        migrations.RemoveField(
            model_name='forecastreport',
            name='forecasted_net_profit',
        ),
        migrations.RemoveField(
            model_name='forecastreport',
            name='is_finalized',
        ),
        migrations.RemoveField(
            model_name='forecastreport',
            name='version',
        ),
    ]
