# Generated by Django 5.2.4 on 2025-08-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analytics', '0003_alter_forecastreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastreport',
            name='base_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
