# Generated by Django 5.2.4 on 2025-08-13 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('main_partner', 'Main Partner'), ('partner', 'Partner'), ('viewer', 'Viewer')], default='partner', max_length=20)),
                ('permissions', models.CharField(choices=[('all', 'All Permissions'), ('limited', 'Limited Permissions'), ('view_only', 'View Only')], default='limited', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
