# Generated by Django 5.2.4 on 2025-08-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dailytask', '0001_initial'),
        ('projects', '0001_initial'),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlinenotification',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadline_notifications', to='sprints.sprint'),
        ),
        migrations.AddField(
            model_name='deadlinenotification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadline_notifications', to='dailytask.dailytask'),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='dailytask.dailytask'),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='deadlinenotification',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadline_notifications', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.client'),
        ),
    ]
