# Generated by Django 5.2.4 on 2025-08-13 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_initial'),
        ('sprints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='team_members',
            field=models.ManyToManyField(related_name='sprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retrospective',
            name='sprint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrospective', to='sprints.sprint'),
        ),
        migrations.AddField(
            model_name='story',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='projects.project'),
        ),
        migrations.AddField(
            model_name='story',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='sprints.sprint'),
        ),
    ]
