# Generated by Django 5.2.4 on 2025-08-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        ('financial_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_analytics.costcenter'),
        ),
    ]
