# Generated by Django 5.2.4 on 2025-08-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_cost_center'),
        ('financial_analytics', '0002_alter_taxreport_total_deductions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='financial_analytics.financialperiod'),
        ),
    ]
