# Generated by Django 5.2.4 on 2025-08-20 11:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analytics', '0001_initial'),
        ('income', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_analytics.costcenter'),
        ),
        migrations.AlterField(
            model_name='orgpartnershare',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_partner_shares', to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='PartnerIncomeShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_partner_shares', to='income.invoice')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['invoice', '-amount'],
                'unique_together': {('partner', 'invoice')},
            },
        ),
    ]
