# Generated by Django 5.2.4 on 2025-08-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analytics', '0002_alter_taxreport_total_deductions_and_more'),
        ('income', '0002_invoice_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='financial_analytics.financialperiod'),
        ),
    ]
