# Generated by Django 5.2.4 on 2025-08-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresstracking', '0003_progressupdate_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='progress_reports/'),
        ),
    ]
