# Generated by Django 6.0 on 2026-01-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='email',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='phone',
            new_name='company_phone',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address_line2',
        ),
    ]
