# Generated by Django 5.2.4 on 2025-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('partner', 'Partner'), ('organization_admin', 'Organization Admin'), ('employee', 'Employee')], max_length=20),
        ),
    ]
